export const sectors = [
  {
    id: 1,
    name: "Kiln A",
    risk: "Critical",
    temperature: "82°C",
    gas: "78 ppm",
    pressure: "10.4 bar",
    workers: 8,
    maintenance: "Active",
  },
  {
    id: 2,
    name: "Kiln B",
    risk: "High",
    temperature: "74°C",
    gas: "56 ppm",
    pressure: "9.8 bar",
    workers: 6,
    maintenance: "Inactive",
  },
  {
    id: 3,
    name: "Coal Mill",
    risk: "Medium",
    temperature: "62°C",
    gas: "42 ppm",
    pressure: "8.6 bar",
    workers: 4,
    maintenance: "Inactive",
  },
  {
    id: 4,
    name: "Raw Mill",
    risk: "Low",
    temperature: "48°C",
    gas: "20 ppm",
    pressure: "7.9 bar",
    workers: 5,
    maintenance: "Inactive",
  },
  {
    id: 5,
    name: "Separator",
    risk: "Medium",
    temperature: "59°C",
    gas: "39 ppm",
    pressure: "8.4 bar",
    workers: 3,
    maintenance: "Active",
  },
  {
    id: 6,
    name: "Packing Plant",
    risk: "Low",
    temperature: "42°C",
    gas: "15 ppm",
    pressure: "7.1 bar",
    workers: 10,
    maintenance: "Inactive",
  },
];